version: '3.7'
services:
    postgres_local:
        image: postgres:9.6
        ports:
            - '5430:5432'
        environment:
            - POSTGRES_USER=truefilm_user
            - POSTGRES_PASSWORD=truefilmpass
            - POSTGRES_DB=truefilm_db
            - PGDATA=/var/lib/postgresql/data/pgdata_local
        volumes:
            - pg_data_local:/var/lib/postgresql/data/pgdata_local
        logging:
            options:
                max-size: 10m
                max-file: "3"
                
    postgres:
        image: postgres:9.6
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
            - PGDATA=/var/lib/postgresql/data/pgdata_af
        volumes:
            - pg_data_af:/var/lib/postgresql/data/pgdata_af
        logging:
            options:
                max-size: 10m
                max-file: "3"

    webserver:
        image: puckel/docker-airflow:latest
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./data:/usr/local/airflow/data
            - ./requirements.txt:/requirements.txt
            - ./config/airflow.cfg:/usr/local/airflow/airflow.cfg           
            - ./dags/config/:/usr/local/airflow/config
        ports:
            - "8081:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

volumes: 
    pg_data_af:
        external: true 
    pg_data_local:
        external: true